// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBCvId4Qml_DKsx0ebAfN0mHCYDT4H1wr0',
    appId: '1:361293597999:android:58a3e2bec6450955d8a5da',
    messagingSenderId: '361293597999',
    projectId: 'fir-task-manager-fdba5',
    storageBucket: 'fir-task-manager-fdba5.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAogDEhzJn643sn2iw5r57SS35Qe8d0iEw',
    appId: '1:361293597999:ios:610c55f1c6137336d8a5da',
    messagingSenderId: '361293597999',
    projectId: 'fir-task-manager-fdba5',
    storageBucket: 'fir-task-manager-fdba5.firebasestorage.app',
    androidClientId: '361293597999-hsi3pol0e0f1jah05j160kl4srg7vpfb.apps.googleusercontent.com',
    iosClientId: '361293597999-s5v3gr3rq1le1omoqdd9mu0lie4qse63.apps.googleusercontent.com',
    iosBundleId: 'com.mahirrohan08.firebaseTaskManager',
  );
}
